/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tahubulatdadakan.praktikumpbo.tubespbo;

/**
 *
 * @author User
 */
public class DeveloperPage extends javax.swing.JFrame {

    /**
     * Creates new form GuidePage
     */
    public DeveloperPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tahubulatGambar = new javax.swing.JLabel();
        judul1Label = new javax.swing.JLabel();
        judul2Label = new javax.swing.JLabel();
        rias = new javax.swing.JLabel();
        manager = new javax.swing.JLabel();
        analysis = new javax.swing.JLabel();
        sultan = new javax.swing.JLabel();
        fadhlan = new javax.swing.JLabel();
        designing = new javax.swing.JLabel();
        ari = new javax.swing.JLabel();
        coding = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        backgroundTheme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Bangun Datar dan Ruang");
        setMinimumSize(new java.awt.Dimension(336, 526));

        jPanel1.setMinimumSize(new java.awt.Dimension(336, 526));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tahubulatGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\tahu_bulat_1.png")); // NOI18N
        jPanel1.add(tahubulatGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 240, 220));

        judul1Label.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        judul1Label.setForeground(new java.awt.Color(0, 102, 102));
        judul1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1Label.setText("KELOMPOK");
        jPanel1.add(judul1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 25));

        judul2Label.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        judul2Label.setForeground(new java.awt.Color(0, 204, 204));
        judul2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2Label.setText("TAHU BULAT DADAKAN");
        jPanel1.add(judul2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 20));

        rias.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rias.setText("Rias Gauri Nur Hasanah");
        jPanel1.add(rias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, 30));

        manager.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\clipboard.png")); // NOI18N
        jPanel1.add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        analysis.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\research_1.png")); // NOI18N
        jPanel1.add(analysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        sultan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sultan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sultan.setText("Daffa Sultansyah");
        jPanel1.add(sultan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 120, 30));

        fadhlan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        fadhlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fadhlan.setText("TB. Ahmad Fadhlan Shaquille");
        jPanel1.add(fadhlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 30));

        designing.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\web-design.png")); // NOI18N
        jPanel1.add(designing, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        ari.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ari.setText("Muhammad Ari Al Ghifari");
        jPanel1.add(ari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 170, 30));

        coding.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\coding.png")); // NOI18N
        jPanel1.add(coding, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 102));
        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\homeButton.png")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 30, 30));

        backgroundTheme.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        jPanel1.add(backgroundTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        StartPage sp = new StartPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeveloperPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel analysis;
    private javax.swing.JLabel ari;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundTheme;
    private javax.swing.JLabel coding;
    private javax.swing.JLabel designing;
    private javax.swing.JLabel fadhlan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul1Label;
    private javax.swing.JLabel judul2Label;
    private javax.swing.JLabel manager;
    private javax.swing.JLabel rias;
    private javax.swing.JLabel sultan;
    private javax.swing.JLabel tahubulatGambar;
    // End of variables declaration//GEN-END:variables
}
