/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tahubulatdadakan.praktikumpbo.tubespbo;

/**
 *
 * @author User
 */
public class MenuBangunRuang extends javax.swing.JFrame {

    /**
     * Creates new form MenuBangunDatar
     */
    public MenuBangunRuang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        kubusPanel = new javax.swing.JPanel();
        kubusJudul = new javax.swing.JLabel();
        kubusGambar = new javax.swing.JLabel();
        diketKubus = new javax.swing.JLabel();
        sisiKubus = new javax.swing.JLabel();
        sisiKubusField = new javax.swing.JTextField();
        rumusKubus = new javax.swing.JLabel();
        volumeKubus = new javax.swing.JLabel();
        hasilKubus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasilKubusArea = new javax.swing.JTextArea();
        hitungKubus = new javax.swing.JButton();
        clearKubus = new javax.swing.JButton();
        backKubus = new javax.swing.JButton();
        kubusBackground = new javax.swing.JLabel();
        balokPanel = new javax.swing.JPanel();
        balokJudul = new javax.swing.JLabel();
        balokGambar = new javax.swing.JLabel();
        diketBalok = new javax.swing.JLabel();
        panjangBalok = new javax.swing.JLabel();
        panjangBalokField = new javax.swing.JTextField();
        lebarBalok = new javax.swing.JLabel();
        lebarBalokField = new javax.swing.JTextField();
        tinggiBalok = new javax.swing.JLabel();
        tinggiBalokField = new javax.swing.JTextField();
        rumusBalok = new javax.swing.JLabel();
        volumeBalok = new javax.swing.JLabel();
        hasilBalok = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilBalokArea = new javax.swing.JTextArea();
        clearBalok = new javax.swing.JButton();
        hitungBalok = new javax.swing.JButton();
        backBalok = new javax.swing.JButton();
        balokBackground = new javax.swing.JLabel();
        tabungPanel = new javax.swing.JPanel();
        tabungJudul = new javax.swing.JLabel();
        tabungGambar = new javax.swing.JLabel();
        jariTabung = new javax.swing.JLabel();
        jariTabungField = new javax.swing.JTextField();
        diketTabung = new javax.swing.JLabel();
        tinggiTabung = new javax.swing.JLabel();
        tinggiTabungField = new javax.swing.JTextField();
        phiTabung = new javax.swing.JLabel();
        nilaiphiTabung = new javax.swing.JLabel();
        rumusTabung = new javax.swing.JLabel();
        volumeTabung = new javax.swing.JLabel();
        hasilTabung = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        hasilTabungArea = new javax.swing.JTextArea();
        hitungTabung = new javax.swing.JButton();
        clearTabung = new javax.swing.JButton();
        backTabung = new javax.swing.JButton();
        tabungBackground = new javax.swing.JLabel();
        kerucutPanel = new javax.swing.JPanel();
        kerucutJudul = new javax.swing.JLabel();
        kerucutGambar = new javax.swing.JLabel();
        diketKerucut = new javax.swing.JLabel();
        jariKerucut = new javax.swing.JLabel();
        jariKerucutField = new javax.swing.JTextField();
        tinggiKerucut = new javax.swing.JLabel();
        tinggiKerucutField = new javax.swing.JTextField();
        phiKerucut = new javax.swing.JLabel();
        nilaiphiKerucut = new javax.swing.JLabel();
        rumusKerucut = new javax.swing.JLabel();
        luasKerucut = new javax.swing.JLabel();
        hasilKerucut = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        hasilKerucutArea = new javax.swing.JTextArea();
        hitungKerucut = new javax.swing.JButton();
        clearKerucut = new javax.swing.JButton();
        backKerucut = new javax.swing.JButton();
        KerucutBackground = new javax.swing.JLabel();
        bolaPanel = new javax.swing.JPanel();
        bolaJudul = new javax.swing.JLabel();
        bolaGambar = new javax.swing.JLabel();
        diketBola = new javax.swing.JLabel();
        jariBola = new javax.swing.JLabel();
        jariBolaField = new javax.swing.JTextField();
        phiBola = new javax.swing.JLabel();
        nilaiphiBola = new javax.swing.JLabel();
        rumusBola = new javax.swing.JLabel();
        volumeBola = new javax.swing.JLabel();
        hasilBola = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        hasilBolaArea = new javax.swing.JTextArea();
        hitungBola = new javax.swing.JButton();
        clearBola = new javax.swing.JButton();
        backBola = new javax.swing.JButton();
        bolaBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Bangun Datar dan Ruang");
        setMinimumSize(new java.awt.Dimension(336, 526));

        jTabbedPane1.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(336, 526));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(336, 526));

        kubusPanel.setLayout(null);

        kubusJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        kubusJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kubusJudul.setText("KUBUS");
        kubusPanel.add(kubusJudul);
        kubusJudul.setBounds(120, 30, 90, 30);

        kubusGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\kubus_tab.png")); // NOI18N
        kubusPanel.add(kubusGambar);
        kubusGambar.setBounds(120, 60, 100, 110);

        diketKubus.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketKubus.setText("Diketahui :");
        kubusPanel.add(diketKubus);
        diketKubus.setBounds(40, 170, 64, 18);

        sisiKubus.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        sisiKubus.setText("sisi =");
        kubusPanel.add(sisiKubus);
        sisiKubus.setBounds(70, 190, 30, 20);

        sisiKubusField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kubusPanel.add(sisiKubusField);
        sisiKubusField.setBounds(110, 190, 50, 24);

        rumusKubus.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusKubus.setText("Rumus   :");
        kubusPanel.add(rumusKubus);
        rumusKubus.setBounds(40, 220, 55, 18);

        volumeKubus.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        volumeKubus.setText("Volume = sisi ^ 3");
        kubusPanel.add(volumeKubus);
        volumeKubus.setBounds(110, 220, 93, 18);

        hasilKubus.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilKubus.setText("Hasil    :");
        kubusPanel.add(hasilKubus);
        hasilKubus.setBounds(40, 250, 53, 18);

        hasilKubusArea.setColumns(20);
        hasilKubusArea.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hasilKubusArea.setRows(5);
        jScrollPane2.setViewportView(hasilKubusArea);

        kubusPanel.add(jScrollPane2);
        jScrollPane2.setBounds(110, 250, 150, 70);

        hitungKubus.setBackground(new java.awt.Color(153, 255, 153));
        hitungKubus.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungKubus.setText("Hitung");
        hitungKubus.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungKubusActionPerformed(evt);
            }
        });
        kubusPanel.add(hitungKubus);
        hitungKubus.setBounds(180, 370, 60, 20);

        clearKubus.setBackground(new java.awt.Color(255, 51, 51));
        clearKubus.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearKubus.setText("Clear");
        clearKubus.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearKubusActionPerformed(evt);
            }
        });
        kubusPanel.add(clearKubus);
        clearKubus.setBounds(100, 370, 60, 20);

        backKubus.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backKubus.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backKubus.setBorderPainted(false);
        backKubus.setContentAreaFilled(false);
        backKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backKubusActionPerformed(evt);
            }
        });
        kubusPanel.add(backKubus);
        backKubus.setBounds(150, 400, 40, 30);

        kubusBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        kubusBackground.setText("jLabel1");
        kubusPanel.add(kubusBackground);
        kubusBackground.setBounds(0, 0, 336, 500);

        jTabbedPane1.addTab("Kubus", kubusPanel);

        balokPanel.setLayout(null);

        balokJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        balokJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balokJudul.setText("BALOK");
        balokPanel.add(balokJudul);
        balokJudul.setBounds(70, 40, 200, 30);

        balokGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\balok_tab.png")); // NOI18N
        balokPanel.add(balokGambar);
        balokGambar.setBounds(100, 60, 150, 120);

        diketBalok.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketBalok.setText("Diketahui :");
        balokPanel.add(diketBalok);
        diketBalok.setBounds(40, 180, 64, 18);

        panjangBalok.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        panjangBalok.setText("panjang =");
        balokPanel.add(panjangBalok);
        panjangBalok.setBounds(50, 200, 51, 20);

        panjangBalokField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        balokPanel.add(panjangBalokField);
        panjangBalokField.setBounds(110, 200, 40, 24);

        lebarBalok.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lebarBalok.setText("lebar =");
        balokPanel.add(lebarBalok);
        lebarBalok.setBounds(60, 230, 40, 18);

        lebarBalokField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        balokPanel.add(lebarBalokField);
        lebarBalokField.setBounds(110, 230, 40, 24);

        tinggiBalok.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        tinggiBalok.setText("tinggi =");
        balokPanel.add(tinggiBalok);
        tinggiBalok.setBounds(170, 200, 40, 18);

        tinggiBalokField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        balokPanel.add(tinggiBalokField);
        tinggiBalokField.setBounds(220, 200, 40, 24);

        rumusBalok.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusBalok.setText("Rumus   :");
        balokPanel.add(rumusBalok);
        rumusBalok.setBounds(40, 260, 55, 18);

        volumeBalok.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        volumeBalok.setText("Volume = p * l * t");
        balokPanel.add(volumeBalok);
        volumeBalok.setBounds(110, 260, 96, 18);

        hasilBalok.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilBalok.setText("Hasil    :");
        balokPanel.add(hasilBalok);
        hasilBalok.setBounds(40, 290, 53, 18);

        hasilBalokArea.setColumns(20);
        hasilBalokArea.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hasilBalokArea.setRows(5);
        jScrollPane3.setViewportView(hasilBalokArea);

        balokPanel.add(jScrollPane3);
        jScrollPane3.setBounds(110, 290, 166, 60);

        clearBalok.setBackground(new java.awt.Color(255, 51, 51));
        clearBalok.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearBalok.setText("Clear");
        clearBalok.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBalokActionPerformed(evt);
            }
        });
        balokPanel.add(clearBalok);
        clearBalok.setBounds(100, 370, 60, 20);

        hitungBalok.setBackground(new java.awt.Color(153, 255, 153));
        hitungBalok.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungBalok.setText("Hitung");
        hitungBalok.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBalokActionPerformed(evt);
            }
        });
        balokPanel.add(hitungBalok);
        hitungBalok.setBounds(180, 370, 60, 20);

        backBalok.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backBalok.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backBalok.setBorderPainted(false);
        backBalok.setContentAreaFilled(false);
        backBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBalokActionPerformed(evt);
            }
        });
        balokPanel.add(backBalok);
        backBalok.setBounds(150, 400, 40, 30);

        balokBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        balokBackground.setText("jLabel1");
        balokPanel.add(balokBackground);
        balokBackground.setBounds(0, 0, 336, 500);

        jTabbedPane1.addTab("Balok", balokPanel);

        tabungPanel.setLayout(null);

        tabungJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        tabungJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabungJudul.setText("TABUNG");
        tabungPanel.add(tabungJudul);
        tabungJudul.setBounds(110, 20, 110, 30);

        tabungGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\tabung_tab.png")); // NOI18N
        tabungPanel.add(tabungGambar);
        tabungGambar.setBounds(140, 50, 80, 130);

        jariTabung.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jariTabung.setText("jari-jari =");
        tabungPanel.add(jariTabung);
        jariTabung.setBounds(50, 200, 55, 18);

        jariTabungField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tabungPanel.add(jariTabungField);
        jariTabungField.setBounds(110, 200, 40, 24);

        diketTabung.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketTabung.setText("Diketahui :");
        tabungPanel.add(diketTabung);
        diketTabung.setBounds(40, 180, 64, 18);

        tinggiTabung.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        tinggiTabung.setText("tinggi =");
        tabungPanel.add(tinggiTabung);
        tinggiTabung.setBounds(170, 200, 40, 18);

        tinggiTabungField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tabungPanel.add(tinggiTabungField);
        tinggiTabungField.setBounds(220, 200, 40, 24);

        phiTabung.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        phiTabung.setText("phi =");
        tabungPanel.add(phiTabung);
        phiTabung.setBounds(74, 230, 30, 18);

        nilaiphiTabung.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nilaiphiTabung.setText("22/7");
        tabungPanel.add(nilaiphiTabung);
        nilaiphiTabung.setBounds(110, 230, 27, 18);

        rumusTabung.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusTabung.setText("Rumus   :");
        tabungPanel.add(rumusTabung);
        rumusTabung.setBounds(40, 250, 55, 18);

        volumeTabung.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        volumeTabung.setText("Volume = phi * r^2 * t");
        tabungPanel.add(volumeTabung);
        volumeTabung.setBounds(110, 250, 121, 18);

        hasilTabung.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilTabung.setText("Hasil    :");
        tabungPanel.add(hasilTabung);
        hasilTabung.setBounds(40, 280, 53, 18);

        hasilTabungArea.setColumns(20);
        hasilTabungArea.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hasilTabungArea.setRows(5);
        jScrollPane4.setViewportView(hasilTabungArea);

        tabungPanel.add(jScrollPane4);
        jScrollPane4.setBounds(110, 280, 150, 60);

        hitungTabung.setBackground(new java.awt.Color(153, 255, 153));
        hitungTabung.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungTabung.setText("Hitung");
        hitungTabung.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungTabungActionPerformed(evt);
            }
        });
        tabungPanel.add(hitungTabung);
        hitungTabung.setBounds(180, 370, 60, 20);

        clearTabung.setBackground(new java.awt.Color(255, 51, 51));
        clearTabung.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearTabung.setText("Clear");
        clearTabung.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTabungActionPerformed(evt);
            }
        });
        tabungPanel.add(clearTabung);
        clearTabung.setBounds(100, 370, 60, 20);

        backTabung.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backTabung.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backTabung.setBorderPainted(false);
        backTabung.setContentAreaFilled(false);
        backTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTabungActionPerformed(evt);
            }
        });
        tabungPanel.add(backTabung);
        backTabung.setBounds(150, 400, 40, 30);

        tabungBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        tabungPanel.add(tabungBackground);
        tabungBackground.setBounds(0, 0, 336, 500);

        jTabbedPane1.addTab("Tabung", tabungPanel);

        kerucutPanel.setLayout(null);

        kerucutJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        kerucutJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kerucutJudul.setText("KERUCUT");
        kerucutPanel.add(kerucutJudul);
        kerucutJudul.setBounds(110, 20, 110, 30);

        kerucutGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\kerucut_tab.png")); // NOI18N
        kerucutPanel.add(kerucutGambar);
        kerucutGambar.setBounds(130, 45, 90, 130);

        diketKerucut.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketKerucut.setText("Diketahui :");
        kerucutPanel.add(diketKerucut);
        diketKerucut.setBounds(40, 180, 64, 18);

        jariKerucut.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jariKerucut.setText("jari-jari =");
        kerucutPanel.add(jariKerucut);
        jariKerucut.setBounds(50, 200, 55, 18);

        jariKerucutField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kerucutPanel.add(jariKerucutField);
        jariKerucutField.setBounds(110, 200, 40, 24);

        tinggiKerucut.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        tinggiKerucut.setText("tinggi =");
        kerucutPanel.add(tinggiKerucut);
        tinggiKerucut.setBounds(170, 200, 40, 18);

        tinggiKerucutField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kerucutPanel.add(tinggiKerucutField);
        tinggiKerucutField.setBounds(220, 200, 40, 24);

        phiKerucut.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        phiKerucut.setText("phi =");
        kerucutPanel.add(phiKerucut);
        phiKerucut.setBounds(80, 230, 30, 18);

        nilaiphiKerucut.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nilaiphiKerucut.setText("22/7");
        kerucutPanel.add(nilaiphiKerucut);
        nilaiphiKerucut.setBounds(110, 230, 27, 18);

        rumusKerucut.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusKerucut.setText("Rumus   :");
        kerucutPanel.add(rumusKerucut);
        rumusKerucut.setBounds(40, 250, 55, 18);

        luasKerucut.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        luasKerucut.setText("Volume = 1/3 * phi * r^2 * t");
        kerucutPanel.add(luasKerucut);
        luasKerucut.setBounds(110, 250, 153, 18);

        hasilKerucut.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilKerucut.setText("Hasil    :");
        kerucutPanel.add(hasilKerucut);
        hasilKerucut.setBounds(40, 280, 53, 18);

        hasilKerucutArea.setColumns(20);
        hasilKerucutArea.setRows(5);
        jScrollPane5.setViewportView(hasilKerucutArea);

        kerucutPanel.add(jScrollPane5);
        jScrollPane5.setBounds(110, 280, 150, 70);

        hitungKerucut.setBackground(new java.awt.Color(153, 255, 153));
        hitungKerucut.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungKerucut.setText("Hitung");
        hitungKerucut.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungKerucutActionPerformed(evt);
            }
        });
        kerucutPanel.add(hitungKerucut);
        hitungKerucut.setBounds(180, 370, 60, 20);

        clearKerucut.setBackground(new java.awt.Color(255, 51, 51));
        clearKerucut.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearKerucut.setText("Clear");
        clearKerucut.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearKerucutActionPerformed(evt);
            }
        });
        kerucutPanel.add(clearKerucut);
        clearKerucut.setBounds(100, 370, 60, 20);

        backKerucut.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backKerucut.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backKerucut.setBorderPainted(false);
        backKerucut.setContentAreaFilled(false);
        backKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backKerucutActionPerformed(evt);
            }
        });
        kerucutPanel.add(backKerucut);
        backKerucut.setBounds(150, 400, 40, 30);

        KerucutBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        kerucutPanel.add(KerucutBackground);
        KerucutBackground.setBounds(0, 0, 336, 500);

        jTabbedPane1.addTab("Kerucut", kerucutPanel);

        bolaPanel.setLayout(null);

        bolaJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        bolaJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bolaJudul.setText("BOLA");
        bolaPanel.add(bolaJudul);
        bolaJudul.setBounds(110, 30, 110, 30);

        bolaGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\bola_tab.png")); // NOI18N
        bolaPanel.add(bolaGambar);
        bolaGambar.setBounds(120, 60, 110, 110);

        diketBola.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketBola.setText("Diketahui :");
        bolaPanel.add(diketBola);
        diketBola.setBounds(40, 180, 64, 18);

        jariBola.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jariBola.setText("jari-jari =");
        bolaPanel.add(jariBola);
        jariBola.setBounds(50, 200, 55, 18);

        jariBolaField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bolaPanel.add(jariBolaField);
        jariBolaField.setBounds(110, 200, 40, 24);

        phiBola.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        phiBola.setText("phi =");
        bolaPanel.add(phiBola);
        phiBola.setBounds(80, 230, 30, 18);

        nilaiphiBola.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nilaiphiBola.setText("22/7");
        bolaPanel.add(nilaiphiBola);
        nilaiphiBola.setBounds(110, 230, 27, 18);

        rumusBola.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusBola.setText("Rumus   :");
        bolaPanel.add(rumusBola);
        rumusBola.setBounds(40, 250, 55, 18);

        volumeBola.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        volumeBola.setText("Volume = 4/3 * phi * r^2");
        bolaPanel.add(volumeBola);
        volumeBola.setBounds(110, 250, 135, 18);

        hasilBola.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilBola.setText("Hasil    :");
        bolaPanel.add(hasilBola);
        hasilBola.setBounds(40, 280, 53, 18);

        hasilBolaArea.setColumns(20);
        hasilBolaArea.setRows(5);
        jScrollPane6.setViewportView(hasilBolaArea);

        bolaPanel.add(jScrollPane6);
        jScrollPane6.setBounds(110, 280, 150, 60);

        hitungBola.setBackground(new java.awt.Color(153, 255, 153));
        hitungBola.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungBola.setText("Hitung");
        hitungBola.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBolaActionPerformed(evt);
            }
        });
        bolaPanel.add(hitungBola);
        hitungBola.setBounds(180, 370, 60, 21);

        clearBola.setBackground(new java.awt.Color(255, 51, 51));
        clearBola.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearBola.setText("Clear");
        clearBola.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBolaActionPerformed(evt);
            }
        });
        bolaPanel.add(clearBola);
        clearBola.setBounds(100, 370, 60, 20);

        backBola.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backBola.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backBola.setBorderPainted(false);
        backBola.setContentAreaFilled(false);
        backBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBolaActionPerformed(evt);
            }
        });
        bolaPanel.add(backBola);
        backBola.setBounds(150, 400, 40, 30);

        bolaBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        bolaPanel.add(bolaBackground);
        bolaBackground.setBounds(0, 0, 336, 500);

        jTabbedPane1.addTab("Bola", bolaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungKubusActionPerformed
        double sisi = Double.parseDouble(sisiKubusField.getText());
        double volume = sisi*sisi*sisi;
        hasilKubusArea.setText("Volume : " + sisi + " x " + sisi + " x " + sisi + " = " + String.valueOf(volume));
    }//GEN-LAST:event_hitungKubusActionPerformed

    private void clearKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearKubusActionPerformed
        sisiKubusField.setText("");
        hasilKubusArea.setText("");
    }//GEN-LAST:event_clearKubusActionPerformed

    private void backKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backKubusActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backKubusActionPerformed

    private void clearBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBalokActionPerformed
        panjangBalokField.setText("");
        lebarBalokField.setText("");
        hasilBalokArea.setText("");
    }//GEN-LAST:event_clearBalokActionPerformed

    private void hitungBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBalokActionPerformed
        double panjang = Double.parseDouble(panjangBalokField.getText());
        double lebar = Double.parseDouble(lebarBalokField.getText());
        double tinggi = Double.parseDouble(tinggiBalokField.getText());
        double volume = panjang*lebar*tinggi;
        hasilBalokArea.setText("Volume : " + panjang + " x " + lebar + " x " + tinggi + " = " + String.valueOf(volume));
    }//GEN-LAST:event_hitungBalokActionPerformed

    private void backBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBalokActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBalokActionPerformed

    private void hitungTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungTabungActionPerformed
        double jari = Double.parseDouble(jariTabungField.getText());
        double tinggi = Double.parseDouble(tinggiTabungField.getText());
        double phi = 3.14;
        double volume = phi*jari*jari*tinggi;
        hasilTabungArea.setText("Volume : " + String.valueOf(volume));
    }//GEN-LAST:event_hitungTabungActionPerformed

    private void clearTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTabungActionPerformed
        jariTabungField.setText("");
        tinggiTabungField.setText("");
        hasilTabungArea.setText("");
    }//GEN-LAST:event_clearTabungActionPerformed

    private void backTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTabungActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backTabungActionPerformed

    private void hitungKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungKerucutActionPerformed
        double r = Double.parseDouble(jariKerucutField.getText());
        double t = Double.parseDouble(tinggiKerucutField.getText());
        double phi = 3.14;
        double volume = (1/3)*phi*r*r*t;
        hasilKerucutArea.setText("Volume : " + String.valueOf(volume));
    }//GEN-LAST:event_hitungKerucutActionPerformed

    private void clearKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearKerucutActionPerformed
        jariKerucutField.setText("");
        tinggiKerucutField.setText("");
        hasilKerucutArea.setText("");
    }//GEN-LAST:event_clearKerucutActionPerformed

    private void backKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backKerucutActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backKerucutActionPerformed

    private void hitungBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBolaActionPerformed
        double r = Double.parseDouble(jariBolaField.getText());
        double phi = 3.14;
        double volume = (4/3)*phi*r*r;
        hasilBolaArea.setText("Volume : " + String.valueOf(volume));
    }//GEN-LAST:event_hitungBolaActionPerformed

    private void clearBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBolaActionPerformed
        jariBolaField.setText("");        
        hasilBolaArea.setText("");
    }//GEN-LAST:event_clearBolaActionPerformed

    private void backBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBolaActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KerucutBackground;
    private javax.swing.JButton backBalok;
    private javax.swing.JButton backBola;
    private javax.swing.JButton backKerucut;
    private javax.swing.JButton backKubus;
    private javax.swing.JButton backTabung;
    private javax.swing.JLabel balokBackground;
    private javax.swing.JLabel balokGambar;
    private javax.swing.JLabel balokJudul;
    private javax.swing.JPanel balokPanel;
    private javax.swing.JLabel bolaBackground;
    private javax.swing.JLabel bolaGambar;
    private javax.swing.JLabel bolaJudul;
    private javax.swing.JPanel bolaPanel;
    private javax.swing.JButton clearBalok;
    private javax.swing.JButton clearBola;
    private javax.swing.JButton clearKerucut;
    private javax.swing.JButton clearKubus;
    private javax.swing.JButton clearTabung;
    private javax.swing.JLabel diketBalok;
    private javax.swing.JLabel diketBola;
    private javax.swing.JLabel diketKerucut;
    private javax.swing.JLabel diketKubus;
    private javax.swing.JLabel diketTabung;
    private javax.swing.JLabel hasilBalok;
    private javax.swing.JTextArea hasilBalokArea;
    private javax.swing.JLabel hasilBola;
    private javax.swing.JTextArea hasilBolaArea;
    private javax.swing.JLabel hasilKerucut;
    private javax.swing.JTextArea hasilKerucutArea;
    private javax.swing.JLabel hasilKubus;
    private javax.swing.JTextArea hasilKubusArea;
    private javax.swing.JLabel hasilTabung;
    private javax.swing.JTextArea hasilTabungArea;
    private javax.swing.JButton hitungBalok;
    private javax.swing.JButton hitungBola;
    private javax.swing.JButton hitungKerucut;
    private javax.swing.JButton hitungKubus;
    private javax.swing.JButton hitungTabung;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jariBola;
    private javax.swing.JTextField jariBolaField;
    private javax.swing.JLabel jariKerucut;
    private javax.swing.JTextField jariKerucutField;
    private javax.swing.JLabel jariTabung;
    private javax.swing.JTextField jariTabungField;
    private javax.swing.JLabel kerucutGambar;
    private javax.swing.JLabel kerucutJudul;
    private javax.swing.JPanel kerucutPanel;
    private javax.swing.JLabel kubusBackground;
    private javax.swing.JLabel kubusGambar;
    private javax.swing.JLabel kubusJudul;
    private javax.swing.JPanel kubusPanel;
    private javax.swing.JLabel lebarBalok;
    private javax.swing.JTextField lebarBalokField;
    private javax.swing.JLabel luasKerucut;
    private javax.swing.JLabel nilaiphiBola;
    private javax.swing.JLabel nilaiphiKerucut;
    private javax.swing.JLabel nilaiphiTabung;
    private javax.swing.JLabel panjangBalok;
    private javax.swing.JTextField panjangBalokField;
    private javax.swing.JLabel phiBola;
    private javax.swing.JLabel phiKerucut;
    private javax.swing.JLabel phiTabung;
    private javax.swing.JLabel rumusBalok;
    private javax.swing.JLabel rumusBola;
    private javax.swing.JLabel rumusKerucut;
    private javax.swing.JLabel rumusKubus;
    private javax.swing.JLabel rumusTabung;
    private javax.swing.JLabel sisiKubus;
    private javax.swing.JTextField sisiKubusField;
    private javax.swing.JLabel tabungBackground;
    private javax.swing.JLabel tabungGambar;
    private javax.swing.JLabel tabungJudul;
    private javax.swing.JPanel tabungPanel;
    private javax.swing.JLabel tinggiBalok;
    private javax.swing.JTextField tinggiBalokField;
    private javax.swing.JLabel tinggiKerucut;
    private javax.swing.JTextField tinggiKerucutField;
    private javax.swing.JLabel tinggiTabung;
    private javax.swing.JTextField tinggiTabungField;
    private javax.swing.JLabel volumeBalok;
    private javax.swing.JLabel volumeBola;
    private javax.swing.JLabel volumeKubus;
    private javax.swing.JLabel volumeTabung;
    // End of variables declaration//GEN-END:variables
}
