/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tahubulatdadakan.praktikumpbo.tubespbo;

/**
 *
 * @author User
 */
public class MenuBangun extends javax.swing.JFrame {

    /**
     * Creates new form GuidePage
     */
    public MenuBangun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul1Label = new javax.swing.JLabel();
        bangundatarButton1 = new javax.swing.JButton();
        bangundatarButton2 = new javax.swing.JButton();
        bangunruangButton1 = new javax.swing.JButton();
        bangunruangButton2 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        backgroundTheme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Bangun Datar dan Ruang");
        setMinimumSize(new java.awt.Dimension(336, 526));

        jPanel1.setMinimumSize(new java.awt.Dimension(336, 526));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul1Label.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        judul1Label.setForeground(new java.awt.Color(0, 102, 102));
        judul1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1Label.setText("Silahkan Pilih :");
        jPanel1.add(judul1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 25));

        bangundatarButton1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        bangundatarButton1.setForeground(new java.awt.Color(0, 102, 102));
        bangundatarButton1.setText("Bangun Datar");
        bangundatarButton1.setContentAreaFilled(false);
        bangundatarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangundatarButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(bangundatarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, 23));

        bangundatarButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\bangundatar.png")); // NOI18N
        bangundatarButton2.setContentAreaFilled(false);
        bangundatarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangundatarButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(bangundatarButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 80));

        bangunruangButton1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        bangunruangButton1.setForeground(new java.awt.Color(0, 102, 102));
        bangunruangButton1.setText("Bangun Ruang");
        bangunruangButton1.setContentAreaFilled(false);
        bangunruangButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangunruangButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(bangunruangButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, -1));

        bangunruangButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\bangunruang.png")); // NOI18N
        bangunruangButton2.setContentAreaFilled(false);
        bangunruangButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangunruangButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(bangunruangButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, 80));

        backButton.setBackground(new java.awt.Color(255, 255, 102));
        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\homeButton.png")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 30, 30));

        backgroundTheme.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        jPanel1.add(backgroundTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangundatarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangundatarButton1ActionPerformed
        MenuBangunDatar mbd = new MenuBangunDatar();
        mbd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bangundatarButton1ActionPerformed

    private void bangundatarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangundatarButton2ActionPerformed
        MenuBangunDatar mbd = new MenuBangunDatar();
        mbd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bangundatarButton2ActionPerformed

    private void bangunruangButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangunruangButton1ActionPerformed
        MenuBangunRuang mbr = new MenuBangunRuang();
        mbr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bangunruangButton1ActionPerformed

    private void bangunruangButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangunruangButton2ActionPerformed
        MenuBangunRuang mbr = new MenuBangunRuang();
        mbr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bangunruangButton2ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        StartPage sp = new StartPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBangun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBangun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBangun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBangun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBangun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundTheme;
    private javax.swing.JButton bangundatarButton1;
    private javax.swing.JButton bangundatarButton2;
    private javax.swing.JButton bangunruangButton1;
    private javax.swing.JButton bangunruangButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul1Label;
    // End of variables declaration//GEN-END:variables
}
