/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tahubulatdadakan.praktikumpbo.tubespbo;

/**
 *
 * @author User
 */
public class MenuBangunDatar extends javax.swing.JFrame {

    /**
     * Creates new form MenuBangunDatar
     */
    public MenuBangunDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        persegiPanel = new javax.swing.JPanel();
        persegiJudul = new javax.swing.JLabel();
        persegiGambar = new javax.swing.JLabel();
        diketPersegi = new javax.swing.JLabel();
        sisiPersegi = new javax.swing.JLabel();
        sisiPersegiField = new javax.swing.JTextField();
        rumusPersegi = new javax.swing.JLabel();
        luasPersegi = new javax.swing.JLabel();
        hasilPersegi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasilPersegiArea = new javax.swing.JTextArea();
        hitungPersegi = new javax.swing.JButton();
        clearPersegi = new javax.swing.JButton();
        backPersegi = new javax.swing.JButton();
        persegiBackground = new javax.swing.JLabel();
        persegipanjangPanel = new javax.swing.JPanel();
        persegipanjangJudul = new javax.swing.JLabel();
        persegipanjangGambar = new javax.swing.JLabel();
        diketPersegiPanjang = new javax.swing.JLabel();
        panjangPersegiPanjang = new javax.swing.JLabel();
        panjangPersegiPanjangField = new javax.swing.JTextField();
        lebarPersegiPanjang = new javax.swing.JLabel();
        lebarPersegiPanjangField = new javax.swing.JTextField();
        rumusPersegiPanjang = new javax.swing.JLabel();
        luasPersegiPanjang = new javax.swing.JLabel();
        hasilPersegiPanjang = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilPersegiPanjangArea = new javax.swing.JTextArea();
        clearPersegiPanjang = new javax.swing.JButton();
        hitungPersegiPanjang = new javax.swing.JButton();
        backPersegiPanjang = new javax.swing.JButton();
        persegipanjangBackground = new javax.swing.JLabel();
        segitigaPanel = new javax.swing.JPanel();
        segitigaJudul = new javax.swing.JLabel();
        segitigaGambar = new javax.swing.JLabel();
        diketSegitiga = new javax.swing.JLabel();
        alasSegitiga = new javax.swing.JLabel();
        alasSegitigaField = new javax.swing.JTextField();
        tinggiSegitiga = new javax.swing.JLabel();
        tinggiSegitigaField = new javax.swing.JTextField();
        rumusSegitiga = new javax.swing.JLabel();
        luasSegitiga = new javax.swing.JLabel();
        hasilSegitiga = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        hasilSegitigaArea = new javax.swing.JTextArea();
        hitungSegitiga = new javax.swing.JButton();
        clearSegitiga = new javax.swing.JButton();
        backSegitiga = new javax.swing.JButton();
        segitigaBackground = new javax.swing.JLabel();
        lingkaranPanel = new javax.swing.JPanel();
        lingkaranJudul = new javax.swing.JLabel();
        lingkaranGambar = new javax.swing.JLabel();
        diketLingkaran = new javax.swing.JLabel();
        jariLingkaran = new javax.swing.JLabel();
        jariLingkaranField = new javax.swing.JTextField();
        phiLingkaran = new javax.swing.JLabel();
        nilaiphiLingkaran = new javax.swing.JLabel();
        rumusLingkaran = new javax.swing.JLabel();
        luasLingkaran = new javax.swing.JLabel();
        hasilLingkaran = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        hasilLingkaranArea = new javax.swing.JTextArea();
        hitungLingkaran = new javax.swing.JButton();
        clearLingkaran = new javax.swing.JButton();
        backLingkaran = new javax.swing.JButton();
        lingkaranBackground = new javax.swing.JLabel();
        trapesiumPanel = new javax.swing.JPanel();
        trapesiumJudul = new javax.swing.JLabel();
        trapesiumGambar = new javax.swing.JLabel();
        diketTrapesium = new javax.swing.JLabel();
        sisiATrapesium = new javax.swing.JLabel();
        sisiATrapesiumField = new javax.swing.JTextField();
        tinggiTrapesium = new javax.swing.JLabel();
        tinggiTrapesiumField = new javax.swing.JTextField();
        sisiBTrapesium = new javax.swing.JLabel();
        sisiBTrapesiumField = new javax.swing.JTextField();
        rumusTrapesium = new javax.swing.JLabel();
        luasTrapesium = new javax.swing.JLabel();
        hasilTrapesium = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        hasilTrapesiumArea = new javax.swing.JTextArea();
        hitungTrapesium = new javax.swing.JButton();
        clearTrapesium = new javax.swing.JButton();
        backTrapesium = new javax.swing.JButton();
        trapesiumBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Bangun Datar dan Ruang");
        setMinimumSize(new java.awt.Dimension(336, 526));

        jTabbedPane1.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(336, 526));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(336, 526));

        persegiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        persegiJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        persegiJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persegiJudul.setText("PERSEGI");
        persegiPanel.add(persegiJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 30));

        persegiGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\persegi_tab_1.png")); // NOI18N
        persegiPanel.add(persegiGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, 110));

        diketPersegi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketPersegi.setText("Diketahui :");
        persegiPanel.add(diketPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        sisiPersegi.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        sisiPersegi.setText("sisi =");
        persegiPanel.add(sisiPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 30, 20));

        sisiPersegiField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        persegiPanel.add(sisiPersegiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 50, -1));

        rumusPersegi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusPersegi.setText("Rumus   :");
        persegiPanel.add(rumusPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        luasPersegi.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        luasPersegi.setText("Luas = sisi * sisi");
        persegiPanel.add(luasPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        hasilPersegi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilPersegi.setText("Hasil    :");
        persegiPanel.add(hasilPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        hasilPersegiArea.setColumns(20);
        hasilPersegiArea.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hasilPersegiArea.setRows(5);
        jScrollPane2.setViewportView(hasilPersegiArea);

        persegiPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 150, 70));

        hitungPersegi.setBackground(new java.awt.Color(153, 255, 153));
        hitungPersegi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungPersegi.setText("Hitung");
        hitungPersegi.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungPersegiActionPerformed(evt);
            }
        });
        persegiPanel.add(hitungPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, 20));

        clearPersegi.setBackground(new java.awt.Color(255, 51, 51));
        clearPersegi.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearPersegi.setText("Clear");
        clearPersegi.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPersegiActionPerformed(evt);
            }
        });
        persegiPanel.add(clearPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, 20));

        backPersegi.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backPersegi.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backPersegi.setBorderPainted(false);
        backPersegi.setContentAreaFilled(false);
        backPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPersegiActionPerformed(evt);
            }
        });
        persegiPanel.add(backPersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 30));

        persegiBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        persegiBackground.setText("jLabel1");
        persegiPanel.add(persegiBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 336, 480));

        jTabbedPane1.addTab("Persegi", persegiPanel);

        persegipanjangPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        persegipanjangJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        persegipanjangJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persegipanjangJudul.setText("PERSEGI PANJANG");
        persegipanjangPanel.add(persegipanjangJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 200, 30));

        persegipanjangGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\persegipanjang_tab_1.png")); // NOI18N
        persegipanjangPanel.add(persegipanjangGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 210, 120));

        diketPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketPersegiPanjang.setText("Diketahui :");
        persegipanjangPanel.add(diketPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        panjangPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        panjangPersegiPanjang.setText("panjang =");
        persegipanjangPanel.add(panjangPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        panjangPersegiPanjangField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        persegipanjangPanel.add(panjangPersegiPanjangField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, -1));

        lebarPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lebarPersegiPanjang.setText("lebar =");
        persegipanjangPanel.add(lebarPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 40, -1));

        lebarPersegiPanjangField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        persegipanjangPanel.add(lebarPersegiPanjangField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 40, -1));

        rumusPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusPersegiPanjang.setText("Rumus   :");
        persegipanjangPanel.add(rumusPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        luasPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        luasPersegiPanjang.setText("Luas = panjang * lebar");
        persegipanjangPanel.add(luasPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        hasilPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilPersegiPanjang.setText("Hasil    :");
        persegipanjangPanel.add(hasilPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        hasilPersegiPanjangArea.setColumns(20);
        hasilPersegiPanjangArea.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hasilPersegiPanjangArea.setRows(5);
        jScrollPane3.setViewportView(hasilPersegiPanjangArea);

        persegipanjangPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, 60));

        clearPersegiPanjang.setBackground(new java.awt.Color(255, 51, 51));
        clearPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearPersegiPanjang.setText("Clear");
        clearPersegiPanjang.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPersegiPanjangActionPerformed(evt);
            }
        });
        persegipanjangPanel.add(clearPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, 20));

        hitungPersegiPanjang.setBackground(new java.awt.Color(153, 255, 153));
        hitungPersegiPanjang.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungPersegiPanjang.setText("Hitung");
        hitungPersegiPanjang.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungPersegiPanjangActionPerformed(evt);
            }
        });
        persegipanjangPanel.add(hitungPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, 20));

        backPersegiPanjang.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backPersegiPanjang.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backPersegiPanjang.setBorderPainted(false);
        backPersegiPanjang.setContentAreaFilled(false);
        backPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPersegiPanjangActionPerformed(evt);
            }
        });
        persegipanjangPanel.add(backPersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 30));

        persegipanjangBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        persegipanjangBackground.setText("jLabel1");
        persegipanjangPanel.add(persegipanjangBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 336, 480));

        jTabbedPane1.addTab("Persegi Panjang", persegipanjangPanel);

        segitigaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        segitigaJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        segitigaJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segitigaJudul.setText("SEGITIGA");
        segitigaPanel.add(segitigaJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 30));

        segitigaGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\segitiga_tab_1.png")); // NOI18N
        segitigaGambar.setText("jLabel1");
        segitigaPanel.add(segitigaGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, 130));

        diketSegitiga.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketSegitiga.setText("Diketahui :");
        segitigaPanel.add(diketSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        alasSegitiga.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        alasSegitiga.setText("alas =");
        segitigaPanel.add(alasSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        alasSegitigaField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        segitigaPanel.add(alasSegitigaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 40, -1));

        tinggiSegitiga.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        tinggiSegitiga.setText("tinggi =");
        segitigaPanel.add(tinggiSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        tinggiSegitigaField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        segitigaPanel.add(tinggiSegitigaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 40, -1));

        rumusSegitiga.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusSegitiga.setText("Rumus   :");
        segitigaPanel.add(rumusSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        luasSegitiga.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        luasSegitiga.setText("Luas = 1/2 * alas * tinggi");
        segitigaPanel.add(luasSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        hasilSegitiga.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilSegitiga.setText("Hasil    :");
        segitigaPanel.add(hasilSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        hasilSegitigaArea.setColumns(20);
        hasilSegitigaArea.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hasilSegitigaArea.setRows(5);
        jScrollPane4.setViewportView(hasilSegitigaArea);

        segitigaPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, 60));

        hitungSegitiga.setBackground(new java.awt.Color(153, 255, 153));
        hitungSegitiga.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungSegitiga.setText("Hitung");
        hitungSegitiga.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungSegitigaActionPerformed(evt);
            }
        });
        segitigaPanel.add(hitungSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, 20));

        clearSegitiga.setBackground(new java.awt.Color(255, 51, 51));
        clearSegitiga.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearSegitiga.setText("Clear");
        clearSegitiga.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSegitigaActionPerformed(evt);
            }
        });
        segitigaPanel.add(clearSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, 20));

        backSegitiga.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backSegitiga.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backSegitiga.setBorderPainted(false);
        backSegitiga.setContentAreaFilled(false);
        backSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSegitigaActionPerformed(evt);
            }
        });
        segitigaPanel.add(backSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 30));

        segitigaBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        segitigaPanel.add(segitigaBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jTabbedPane1.addTab("Segitiga", segitigaPanel);

        lingkaranPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lingkaranJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        lingkaranJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lingkaranJudul.setText("LINGKARAN");
        lingkaranPanel.add(lingkaranJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 30));

        lingkaranGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\lingkaran_tab_1.png")); // NOI18N
        lingkaranGambar.setText("jLabel1");
        lingkaranPanel.add(lingkaranGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 150, 110));

        diketLingkaran.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketLingkaran.setText("Diketahui :");
        lingkaranPanel.add(diketLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jariLingkaran.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jariLingkaran.setText("jari-jari =");
        lingkaranPanel.add(jariLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jariLingkaranField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lingkaranPanel.add(jariLingkaranField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 40, -1));

        phiLingkaran.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        phiLingkaran.setText("phi =");
        lingkaranPanel.add(phiLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 30, -1));

        nilaiphiLingkaran.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nilaiphiLingkaran.setText("22/7");
        lingkaranPanel.add(nilaiphiLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        rumusLingkaran.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusLingkaran.setText("Rumus   :");
        lingkaranPanel.add(rumusLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        luasLingkaran.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        luasLingkaran.setText("Luas = phi * r^2");
        lingkaranPanel.add(luasLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        hasilLingkaran.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilLingkaran.setText("Hasil    :");
        lingkaranPanel.add(hasilLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        hasilLingkaranArea.setColumns(20);
        hasilLingkaranArea.setRows(5);
        jScrollPane5.setViewportView(hasilLingkaranArea);

        lingkaranPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 150, 70));

        hitungLingkaran.setBackground(new java.awt.Color(153, 255, 153));
        hitungLingkaran.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungLingkaran.setText("Hitung");
        hitungLingkaran.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungLingkaranActionPerformed(evt);
            }
        });
        lingkaranPanel.add(hitungLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, 20));

        clearLingkaran.setBackground(new java.awt.Color(255, 51, 51));
        clearLingkaran.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearLingkaran.setText("Clear");
        clearLingkaran.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLingkaranActionPerformed(evt);
            }
        });
        lingkaranPanel.add(clearLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, 20));

        backLingkaran.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backLingkaran.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backLingkaran.setBorderPainted(false);
        backLingkaran.setContentAreaFilled(false);
        backLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLingkaranActionPerformed(evt);
            }
        });
        lingkaranPanel.add(backLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 30));

        lingkaranBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        lingkaranPanel.add(lingkaranBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jTabbedPane1.addTab("Lingkaran", lingkaranPanel);

        trapesiumPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trapesiumJudul.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        trapesiumJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trapesiumJudul.setText("TRAPESIUM");
        trapesiumPanel.add(trapesiumJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 30));

        trapesiumGambar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\trapesium_tab_1.png")); // NOI18N
        trapesiumPanel.add(trapesiumGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 160, 90));

        diketTrapesium.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        diketTrapesium.setText("Diketahui :");
        trapesiumPanel.add(diketTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        sisiATrapesium.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        sisiATrapesium.setText("sisi a =");
        trapesiumPanel.add(sisiATrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 180, 40, -1));

        sisiATrapesiumField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sisiATrapesiumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiATrapesiumFieldActionPerformed(evt);
            }
        });
        trapesiumPanel.add(sisiATrapesiumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 40, -1));

        tinggiTrapesium.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        tinggiTrapesium.setText("tinggi =");
        trapesiumPanel.add(tinggiTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        tinggiTrapesiumField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tinggiTrapesiumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiTrapesiumFieldActionPerformed(evt);
            }
        });
        trapesiumPanel.add(tinggiTrapesiumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 40, -1));

        sisiBTrapesium.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        sisiBTrapesium.setText("sisi b =");
        trapesiumPanel.add(sisiBTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 210, 40, -1));

        sisiBTrapesiumField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        trapesiumPanel.add(sisiBTrapesiumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 40, -1));

        rumusTrapesium.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rumusTrapesium.setText("Rumus   :");
        trapesiumPanel.add(rumusTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        luasTrapesium.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        luasTrapesium.setText("Luas = 1/2 * (a + b) * t");
        trapesiumPanel.add(luasTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        hasilTrapesium.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        hasilTrapesium.setText("Hasil    :");
        trapesiumPanel.add(hasilTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        hasilTrapesiumArea.setColumns(20);
        hasilTrapesiumArea.setRows(5);
        jScrollPane6.setViewportView(hasilTrapesiumArea);

        trapesiumPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, 60));

        hitungTrapesium.setBackground(new java.awt.Color(153, 255, 153));
        hitungTrapesium.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        hitungTrapesium.setText("Hitung");
        hitungTrapesium.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hitungTrapesium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungTrapesiumActionPerformed(evt);
            }
        });
        trapesiumPanel.add(hitungTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 60, 20));

        clearTrapesium.setBackground(new java.awt.Color(255, 51, 51));
        clearTrapesium.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        clearTrapesium.setText("Clear");
        clearTrapesium.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        clearTrapesium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTrapesiumActionPerformed(evt);
            }
        });
        trapesiumPanel.add(clearTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, 20));

        backTrapesium.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\back.png")); // NOI18N
        backTrapesium.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        backTrapesium.setBorderPainted(false);
        backTrapesium.setContentAreaFilled(false);
        backTrapesium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTrapesiumActionPerformed(evt);
            }
        });
        trapesiumPanel.add(backTrapesium, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 30));

        trapesiumBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        trapesiumPanel.add(trapesiumBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        jTabbedPane1.addTab("Trapesium", trapesiumPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungPersegiActionPerformed
        double sisi = Double.parseDouble(sisiPersegiField.getText());
        double luas = sisi*sisi;
        hasilPersegiArea.setText("Luas : " + sisi + " x " + sisi + " = " + String.valueOf(luas));
    }//GEN-LAST:event_hitungPersegiActionPerformed

    private void clearPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPersegiActionPerformed
        sisiPersegiField.setText("");
        hasilPersegiArea.setText("");
    }//GEN-LAST:event_clearPersegiActionPerformed

    private void backPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPersegiActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backPersegiActionPerformed

    private void clearPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPersegiPanjangActionPerformed
        panjangPersegiPanjangField.setText("");
        lebarPersegiPanjangField.setText("");
        hasilPersegiPanjangArea.setText("");
    }//GEN-LAST:event_clearPersegiPanjangActionPerformed

    private void hitungPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungPersegiPanjangActionPerformed
        double panjang = Double.parseDouble(panjangPersegiPanjangField.getText());
        double lebar = Double.parseDouble(lebarPersegiPanjangField.getText());
        double luas = panjang*lebar;
        hasilPersegiPanjangArea.setText("Luas : " + panjang + " x " + lebar + " = " + String.valueOf(luas));
    }//GEN-LAST:event_hitungPersegiPanjangActionPerformed

    private void backPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPersegiPanjangActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backPersegiPanjangActionPerformed

    private void hitungSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungSegitigaActionPerformed
        double alas = Double.parseDouble(alasSegitigaField.getText());
        double tinggi = Double.parseDouble(tinggiSegitigaField.getText());
        double luas = 0.5*alas*tinggi;
        hasilSegitigaArea.setText("Luas : " + String.valueOf(luas));
    }//GEN-LAST:event_hitungSegitigaActionPerformed

    private void clearSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSegitigaActionPerformed
        alasSegitigaField.setText("");
        tinggiSegitigaField.setText("");
        hasilSegitigaArea.setText("");
    }//GEN-LAST:event_clearSegitigaActionPerformed

    private void backSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSegitigaActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backSegitigaActionPerformed

    private void hitungLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungLingkaranActionPerformed
        double jari = Double.parseDouble(jariLingkaranField.getText());
        double phi = 3.14;
        double luas = phi*jari*jari;
        hasilLingkaranArea.setText("Luas : " + String.valueOf(luas));
    }//GEN-LAST:event_hitungLingkaranActionPerformed

    private void clearLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLingkaranActionPerformed
        jariLingkaranField.setText("");
        hasilLingkaranArea.setText("");
    }//GEN-LAST:event_clearLingkaranActionPerformed

    private void backLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLingkaranActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLingkaranActionPerformed

    private void sisiATrapesiumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiATrapesiumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiATrapesiumFieldActionPerformed

    private void tinggiTrapesiumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiTrapesiumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiTrapesiumFieldActionPerformed

    private void hitungTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungTrapesiumActionPerformed
        double sa = Double.parseDouble(sisiATrapesiumField.getText());
        double sb = Double.parseDouble(sisiBTrapesiumField.getText());
        double tinggi = Double.parseDouble(tinggiTrapesiumField.getText());
        double luas = 0.5 * (sa+sb) * tinggi;
        hasilTrapesiumArea.setText("Luas : " + String.valueOf(luas));
    }//GEN-LAST:event_hitungTrapesiumActionPerformed

    private void clearTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTrapesiumActionPerformed
        sisiATrapesiumField.setText("");
        sisiBTrapesiumField.setText("");
        tinggiTrapesiumField.setText("");
        hasilTrapesiumArea.setText("");
    }//GEN-LAST:event_clearTrapesiumActionPerformed

    private void backTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTrapesiumActionPerformed
        MenuBangun mba = new MenuBangun();
        mba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backTrapesiumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBangunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alasSegitiga;
    private javax.swing.JTextField alasSegitigaField;
    private javax.swing.JButton backLingkaran;
    private javax.swing.JButton backPersegi;
    private javax.swing.JButton backPersegiPanjang;
    private javax.swing.JButton backSegitiga;
    private javax.swing.JButton backTrapesium;
    private javax.swing.JButton clearLingkaran;
    private javax.swing.JButton clearPersegi;
    private javax.swing.JButton clearPersegiPanjang;
    private javax.swing.JButton clearSegitiga;
    private javax.swing.JButton clearTrapesium;
    private javax.swing.JLabel diketLingkaran;
    private javax.swing.JLabel diketPersegi;
    private javax.swing.JLabel diketPersegiPanjang;
    private javax.swing.JLabel diketSegitiga;
    private javax.swing.JLabel diketTrapesium;
    private javax.swing.JLabel hasilLingkaran;
    private javax.swing.JTextArea hasilLingkaranArea;
    private javax.swing.JLabel hasilPersegi;
    private javax.swing.JTextArea hasilPersegiArea;
    private javax.swing.JLabel hasilPersegiPanjang;
    private javax.swing.JTextArea hasilPersegiPanjangArea;
    private javax.swing.JLabel hasilSegitiga;
    private javax.swing.JTextArea hasilSegitigaArea;
    private javax.swing.JLabel hasilTrapesium;
    private javax.swing.JTextArea hasilTrapesiumArea;
    private javax.swing.JButton hitungLingkaran;
    private javax.swing.JButton hitungPersegi;
    private javax.swing.JButton hitungPersegiPanjang;
    private javax.swing.JButton hitungSegitiga;
    private javax.swing.JButton hitungTrapesium;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jariLingkaran;
    private javax.swing.JTextField jariLingkaranField;
    private javax.swing.JLabel lebarPersegiPanjang;
    private javax.swing.JTextField lebarPersegiPanjangField;
    private javax.swing.JLabel lingkaranBackground;
    private javax.swing.JLabel lingkaranGambar;
    private javax.swing.JLabel lingkaranJudul;
    private javax.swing.JPanel lingkaranPanel;
    private javax.swing.JLabel luasLingkaran;
    private javax.swing.JLabel luasPersegi;
    private javax.swing.JLabel luasPersegiPanjang;
    private javax.swing.JLabel luasSegitiga;
    private javax.swing.JLabel luasTrapesium;
    private javax.swing.JLabel nilaiphiLingkaran;
    private javax.swing.JLabel panjangPersegiPanjang;
    private javax.swing.JTextField panjangPersegiPanjangField;
    private javax.swing.JLabel persegiBackground;
    private javax.swing.JLabel persegiGambar;
    private javax.swing.JLabel persegiJudul;
    private javax.swing.JPanel persegiPanel;
    private javax.swing.JLabel persegipanjangBackground;
    private javax.swing.JLabel persegipanjangGambar;
    private javax.swing.JLabel persegipanjangJudul;
    private javax.swing.JPanel persegipanjangPanel;
    private javax.swing.JLabel phiLingkaran;
    private javax.swing.JLabel rumusLingkaran;
    private javax.swing.JLabel rumusPersegi;
    private javax.swing.JLabel rumusPersegiPanjang;
    private javax.swing.JLabel rumusSegitiga;
    private javax.swing.JLabel rumusTrapesium;
    private javax.swing.JLabel segitigaBackground;
    private javax.swing.JLabel segitigaGambar;
    private javax.swing.JLabel segitigaJudul;
    private javax.swing.JPanel segitigaPanel;
    private javax.swing.JLabel sisiATrapesium;
    private javax.swing.JTextField sisiATrapesiumField;
    private javax.swing.JLabel sisiBTrapesium;
    private javax.swing.JTextField sisiBTrapesiumField;
    private javax.swing.JLabel sisiPersegi;
    private javax.swing.JTextField sisiPersegiField;
    private javax.swing.JLabel tinggiSegitiga;
    private javax.swing.JTextField tinggiSegitigaField;
    private javax.swing.JLabel tinggiTrapesium;
    private javax.swing.JTextField tinggiTrapesiumField;
    private javax.swing.JLabel trapesiumBackground;
    private javax.swing.JLabel trapesiumGambar;
    private javax.swing.JLabel trapesiumJudul;
    private javax.swing.JPanel trapesiumPanel;
    // End of variables declaration//GEN-END:variables
}
