/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tahubulatdadakan.praktikumpbo.tubespbo;

import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form GuidePage
     */
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul1Label = new javax.swing.JLabel();
        judul2Label = new javax.swing.JLabel();
        kalkulatorLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        howtoButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();
        devButton = new javax.swing.JButton();
        backgroundTheme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Bangun Datar dan Ruang");
        setMinimumSize(new java.awt.Dimension(336, 526));

        jPanel1.setMinimumSize(new java.awt.Dimension(336, 526));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul1Label.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        judul1Label.setForeground(new java.awt.Color(0, 102, 102));
        judul1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1Label.setText("KALKULATOR");
        jPanel1.add(judul1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 280, 25));

        judul2Label.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        judul2Label.setForeground(new java.awt.Color(0, 204, 204));
        judul2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2Label.setText("BANGUN DATAR & BANGUN RUANG");
        jPanel1.add(judul2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 260, 20));

        kalkulatorLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\calculator.png")); // NOI18N
        jPanel1.add(kalkulatorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, -1));

        startButton.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        startButton.setForeground(new java.awt.Color(0, 102, 102));
        startButton.setText("START!");
        startButton.setContentAreaFilled(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 100, 30));

        howtoButton.setFont(new java.awt.Font("Ink Free", 1, 11)); // NOI18N
        howtoButton.setForeground(new java.awt.Color(0, 102, 102));
        howtoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\howtousebutton.png")); // NOI18N
        howtoButton.setContentAreaFilled(false);
        howtoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howtoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(howtoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 30, 30));

        outButton.setFont(new java.awt.Font("Ink Free", 1, 11)); // NOI18N
        outButton.setForeground(new java.awt.Color(0, 102, 102));
        outButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\outbutton.png")); // NOI18N
        outButton.setContentAreaFilled(false);
        outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButtonActionPerformed(evt);
            }
        });
        jPanel1.add(outButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 30, 30));

        devButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\user.png")); // NOI18N
        devButton.setContentAreaFilled(false);
        devButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devButtonActionPerformed(evt);
            }
        });
        jPanel1.add(devButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 40, 30));

        backgroundTheme.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TubesPBO\\src\\main\\java\\com\\tahubulatdadakan\\praktikumpbo\\tubespbo\\img\\background2_2.png")); // NOI18N
        backgroundTheme.setText("FKFKFLEJIFJIEIJEFI");
        jPanel1.add(backgroundTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        MenuBangun mb = new MenuBangun();
        mb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startButtonActionPerformed

    private void howtoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howtoButtonActionPerformed
        JOptionPane.showMessageDialog(this, "How to use this app :\n"
            + "1. Just click Start, then pick either 2D or 3D shapes,\n2. Pick the shape,\n3. Put in the requirements, done.\n\n" + "Cara menggunakan aplikasi ini :\n" + "1. Klik Star, lalu pilih bangun datar atau bangun ruang,\n2. Pilih salah satu bangun-nya,\n3. Masukkan semua diketahui-nya, selesai.", "How To Use?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_howtoButtonActionPerformed

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
        int jawab = JOptionPane.showOptionDialog(this, "Ingin Keluar?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi kami ( ͡ᵔ ͜ʖ ͡ᵔ )!");
            System.exit(0);
        }
    }//GEN-LAST:event_outButtonActionPerformed

    private void devButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devButtonActionPerformed
        DeveloperPage dp = new DeveloperPage();
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_devButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundTheme;
    private javax.swing.JButton devButton;
    private javax.swing.JButton howtoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul1Label;
    private javax.swing.JLabel judul2Label;
    private javax.swing.JLabel kalkulatorLabel;
    private javax.swing.JButton outButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
